<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}"  @class(['dark' => ($appearance ?? 'system') == 'dark'])>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {{-- Inline script to detect system dark mode preference and apply it immediately --}}
        <script>
            (function() {
                const appearance = '{{ $appearance ?? "system" }}';

                if (appearance === 'system') {
                    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

                    if (prefersDark) {
                        document.documentElement.classList.add('dark');
                    }
                }
            })();
        </script>

        {{-- Inline style to set the HTML background color based on our theme in app.css --}}
        <style>
            html {
                background-color: oklch(1 0 0);
            }

            html.dark {
                background-color: oklch(0.145 0 0);
            }
        </style>

        <title inertia>{{ config('app.name', 'Laravel') }}</title>

        <link rel="icon" href="/favicon.ico" sizes="any">
        <link rel="icon" href="/favicon.svg" type="image/svg+xml">
        <link rel="apple-touch-icon" href="/apple-touch-icon.png">

        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet" />

        <title>FitnessAI - Personalized AI Workout Plans in 60 Seconds</title>
        <meta name="title" content="FitnessAI - Personalized AI Workout Plans in 60 Seconds">
        <meta name="description" content="Get your personalized 28-day workout plan in 60 seconds. AI-generated workouts + nutrition plans based on your goal, level & equipment. Start free today!">

        <!-- Canonical URL -->
        <link rel="canonical" href="{{ url()->current() }}">

        <!-- Language -->
        <meta http-equiv="content-language" content="en-US">

        <!-- Theme Color -->
        <meta name="theme-color" content="#667eea">

        <!-- Robots -->
        <meta name="robots" content="index, follow, max-image-preview:large">

        <!-- Open Graph / Facebook -->
        <meta property="og:type" content="website">
        <meta property="og:url" content="{{ url()->current() }}">
        <meta property="og:title" content="FitnessAI - Your Personal AI Trainer">
        <meta property="og:description" content="Get your personalized 28-day workout plan in 60 seconds. AI-generated workouts + nutrition plans for muscle gain, fat loss, or endurance.">
        <meta property="og:image" content="{{ asset('images/og-image.jpg') }}">
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="630">

        <!-- Twitter -->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:url" content="{{ url()->current() }}">
        <meta name="twitter:title" content="FitnessAI - Personalized AI Workout Plans in 60 Seconds">
        <meta name="twitter:description" content="28-day workout plans + nutrition, generated by AI. Customized to your goal, level & equipment. Start now!">
        <meta name="twitter:image" content="{{ asset('images/og-image.jpg') }}">


        @vite(['resources/js/app.ts', "resources/js/pages/{$page['component']}.vue"])
        @inertiaHead
    </head>
    <body class="font-sans antialiased bg-dark-surfaces-900">
        @inertia
    </body>
</html>
