<?php

return [
    'plan_ready' => [
        'subject' => 'Your Fitness Plan is Ready 💪',
        'greeting' => 'Hi :name,',
        'thank_you' => 'Thank you for choosing fitnessAI! Your personalized :days-day plan is ready and attached to this email.',
        'tailored' => "We've tailored everything to your specific goals and fitness level:",
        'features' => [
            'meals' => ':days days of meal plans with detailed recipes',
            'workouts' => 'Custom workout routines matched to your fitness level',
            'ingredients' => 'Complete ingredient lists and cooking instructions',
            'exercises' => 'Exercise guides with proper form tips',
        ],
        'review' => 'Please take a moment to review your plans. If you have any questions or need adjustments, we\'re here to help - just reply to this email.',
        'disclaimer_title' => '**Important Disclaimer:**',
        'disclaimer_text' => 'This plan is generated by an AI algorithm and is not a substitute for professional medical or nutritional advice. Please consult with a healthcare professional or licensed dietitian before making any significant changes to your diet or exercise routine.',
        'confidence' => "We're confident this plan will help you reach your goals. Good luck, and enjoy the process!",
        'signature' => 'Best regards,',
        'team' => 'The fitnessAI Team',
    ],

    'verify_email' => [
        'subject' => 'One Step Away from Your Personal Fitness Plan',
        'greeting' => 'Hi :name,',
        'thanks' => 'Thanks for signing up! You\'re one click away from getting your personalized :days-day plan.',
        'verify_text' => 'Just verify your email address to get started:',
        'verify_button' => 'Verify Email Address',
        'what_next' => '**What happens next:**',
        'steps' => [
            'create' => 'We\'ll create your custom meal and workout plans',
            'receive' => 'You\'ll receive everything as PDF attachments',
            'ready' => 'Ready to use in about 3-5 minutes',
        ],
        'valid' => 'The verification link is valid for 24 hours.',
        'ignore' => 'Didn\'t sign up? You can safely ignore this email.',
        'signature' => 'See you soon!',
    ],
];

