<?php

return [
    'plan_ready' => [
        'subject' => 'Your Fitness Plan is Ready 💪',
        'greeting' => 'Hi :name,',
        'thank_you' => 'Thank you for choosing fytrr! Your personalized :days-day plan is ready and attached to this email.',
        'tailored' => "We've tailored everything to your specific goals and fitness level:",
        'features' => [
            'meals' => ':days days of meal plans with detailed recipes',
            'workouts' => 'Custom workout routines matched to your fitness level',
            'ingredients' => 'Complete ingredient lists and cooking instructions',
            'exercises' => 'Exercise guides with proper form tips',
        ],
        'review' => 'Please take a moment to review your plans. If you have any questions or need adjustments, we\'re here to help - just reply to this email.',
        'disclaimer_title' => '**Important Disclaimer:**',
        'disclaimer_text' => 'This plan is generated by an AI algorithm and is not a substitute for professional medical or nutritional advice. Please consult with a healthcare professional or licensed dietitian before making any significant changes to your diet or exercise routine.',
        'confidence' => "We're confident this plan will help you reach your goals. Good luck, and enjoy the process!",
        'signature' => 'Best regards,',
        'team' => 'The fytrr Team',
    ],

    'verify_email' => [
        'subject' => 'One Step Away from Your Personal Fitness Plan',
        'greeting' => 'Hi :name,',
        'thanks' => 'Thanks for signing up! You\'re one click away from getting your personalized :days-day plan.',
        'verify_text' => 'Just verify your email address to get started:',
        'verify_button' => 'Verify Email Address',
        'what_next' => '**What happens next:**',
        'steps' => [
            'create' => 'We\'ll create your custom meal and workout plans',
            'receive' => 'You\'ll receive everything as PDF attachments',
            'ready' => 'Ready to use in about 3-5 minutes',
        ],
        'valid' => 'The verification link is valid for 24 hours.',
        'ignore' => 'Didn\'t sign up? You can safely ignore this email.',
        'signature' => 'See you soon!',
    ],
    'beta_invite' => [
        'subject' => 'Welcome to fytrr – Your Beta Access! 🎉',
        'greeting' => 'Hey :name!',
        'intro' => 'You\'re in! We\'re thrilled to welcome you as a beta tester for fytrr.',
        'description' => 'fytrr is your personal AI fitness coach that guides you through workouts and nutrition. And you\'re among the first to experience it.',
        'steps_title' => '**Here\'s how to get started:**',
        'step_1' => '1️⃣ [Download the fytrr app](:app_store_url) from the App Store',
        'step_2' => '2️⃣ Click the button below to set your password',
        'step_3' => '3️⃣ Sign in to the app and start your journey!',
        'action' => 'Set Password',
        'link_expiry' => 'This link will expire in 24 hours.',
        'feedback' => '**Your feedback matters!** As a beta tester, you have a unique opportunity to shape fytrr. We can\'t wait to hear what you think.',
        'instagram' => '📱 Follow us on Instagram [@getfytrr](https://instagram.com/getfytrr) for updates, tips, and behind-the-scenes content.',
        'support' => 'If you have any questions or run into issues, don\'t hesitate to reach out.',
        'salutation' => 'Happy training,',
        'signature' => 'The fytrr Team',
    ],
];

