<?php

namespace App\Notifications;

use App\Models\Plan;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Barryvdh\DomPDF\Facade\Pdf as PDF;

class PlanGenerationComplete extends Notification implements ShouldQueue
{
    use Queueable;

    /**
     * Create a new notification instance.
     */
    public function __construct(
        public Plan $plan
    ) {}

    /**
     * Get the notification's delivery channels.
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        // Load plan with all relations for PDF generation
        $this->plan->load(['mealPlans.meals', 'workoutPlans.exercises']);

        // Generate Meal Plan PDF
        $mealPlanPdf = PDF::loadView('pdf.nutrition_plan', [
            'user' => $notifiable,
            'plan' => $this->plan,
            'mealPlans' => $this->plan->mealPlans()->with('meals')->orderBy('day_number')->get(),
        ]);

        // Generate Workout Plan PDF
        $workoutPlanPdf = PDF::loadView('pdf.workout_plan', [
            'user' => $notifiable,
            'plan' => $this->plan,
            'workoutPlans' => $this->plan->workoutPlans()->with('exercises')->orderBy('day_number')->get(),
        ]);

        return (new MailMessage)
            ->subject('Your Fitness Plan is Ready 💪')
            ->greeting('Hi ' . $notifiable->name . ',')
            ->line('Thank you for choosing fitnessAI! Your personalized ' . config('plans.duration_days') . '-day plan is ready and attached to this email.')
            ->line('We\'ve tailored everything to your specific goals and fitness level:')
            ->line('• ' . config('plans.duration_days') . ' days of meal plans with detailed recipes')
            ->line('• Custom workout routines matched to your fitness level')
            ->line('• Complete ingredient lists and cooking instructions')
            ->line('• Exercise guides with proper form tips')
            ->line('Please take a moment to review your plans. If you have any questions or need adjustments, we\'re here to help - just reply to this email.')
            ->attachData($mealPlanPdf->output(), 'Meal_Plan_' . $this->plan->id . '.pdf', [
                'mime' => 'application/pdf',
            ])
            ->attachData($workoutPlanPdf->output(), 'Workout_Plan_' . $this->plan->id . '.pdf', [
                'mime' => 'application/pdf',
            ])
            ->line('**Important Disclaimer:**')
            ->line('This plan is generated by an AI algorithm and is not a substitute for professional medical or nutritional advice. Please consult with a healthcare professional or licensed dietitian before making any significant changes to your diet or exercise routine.')
            ->line('We\'re confident this plan will help you reach your goals. Good luck, and enjoy the process!')
            ->line('')
            ->line('')
            ->line('')
            ->line('Best regards,')
            ->salutation('Tobi from fitnessAI.me');
    }

    /**
     * Get the array representation of the notification.
     */
    public function toArray(object $notifiable): array
    {
        return [
            'plan_id' => $this->plan->id,
            'plan_name' => $this->plan->plan_name,
        ];
    }
}

