import {
    Armchair,
    Dumbbell,
    Fish,
    Flame,
    Footprints,
    Hammer,
    Heart,
    HouseHeart,
    Leaf,
    Mars,
    NonBinary,
    PersonStanding,
    Salad,
    Sprout,
    TrendingUp,
    Trophy,
    UtensilsCrossed,
    Venus,
} from 'lucide-vue-next';

export const iconRegistry = {
    mars: Mars,
    venus: Venus,
    nonBinary: NonBinary,
    dumbbell: Dumbbell,
    houseHeart: HouseHeart,
    leaf: Leaf,
    sprout: Sprout,
    utensilsCrossed: UtensilsCrossed,
    salad: Salad,
    fish: Fish,
    flame: Flame,
    heart: Heart,
    armchair: Armchair,
    personStanding: PersonStanding,
    footprints: Footprints,
    hammer: Hammer,
    trendingUp: TrendingUp,
    trophy: Trophy,
} as const;

export type IconName = keyof typeof iconRegistry;
